#!/usr/bin/env python3
# Copyright 2009-2017 BHG http://bw.org/

count = 0
pw = input("Enter a 4 digit integer to be the password:\n")

while count < 6:
    count += 1
    print(f"count = {count}")
    ask1 = input("What is the password?:\n")
    if ask1 == pw:
        print("That is correct")
        break
    else:
        continue
