#!/usr/bin/env python3
# Copyright 2009-2017 BHG http://bw.org/

import random

## Defines variable count
count = 0

## Selects a random 4 digit number to be the password:
pw = random.randint(1000,9999)

# The user CAN ALSO enter a password to be the password, but that would not be as secure
#pw = input("Enter a 4 digit integer to be the password:\n")

## User enters how many attempts they would like to have:
attempts = int(input("How many attempts would you like to have:\n"))

## While loop to check if the password is correct and that the user cannot have more attempts than they asked for
while count < attempts:
    count += 1
    print(f"count = {count}")
    ask1 = input("What is the password?:\n")
    if ask1 == pw:
        print(f"{pw} is the correct password")
        break
    else:
        continue

# If the user cannot correctly identify the password in the given attempts, the following prints:
if count == attempts and ask1 != pw:
    print(f"You have been unable to correctly idetify the password in {attempts} attempt(s).")
